# Generated by Django 3.0.2 on 2020-01-03 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_url', models.CharField(max_length=6, unique=True)),
                ('redirect_location', models.CharField(max_length=256)),
                ('expiration_date', models.DateTimeField(null=True)),
                ('created', models.DateTimeField()),
                ('author_ip', models.GenericIPAddressField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LinkAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_ip_address', models.GenericIPAddressField()),
                ('action_datetime', models.DateTimeField()),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='api.Link')),
            ],
        ),
    ]
